{% set name = "google-cloud-monitoring" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2a25f7535f21cdeabfccb07fe4a75eae5a47bb36b82025537755b37d3376da46

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.28.0,<3.0.0dev
    - proto-plus >=1.15.0

test:
  imports:
    - google.cloud.monitoring
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-monitoring
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Client for Stackdriver Monitoring API
  description: Python idiomatic client for Google Stackdriver Monitoring
  doc_url: https://googleapis.dev/python/monitoring/latest/index.html

extra:
  recipe-maintainers:
    - parthea
    - xylar
