{% set name = "google-cloud-monitoring" %}
{% set version = "2.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-monitoring-{{ version }}.tar.gz
  sha256: 9eda0aa36e95776e18c0425fa82558d44f4bda9e0673d65c2a495c599ade990c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - google-api-core-grpc >=1.33.2,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google.cloud.monitoring
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-monitoring
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Client for Stackdriver Monitoring API
  description: Python idiomatic client for Google Stackdriver Monitoring
  doc_url: https://googleapis.dev/python/monitoring/latest/index.html

extra:
  recipe-maintainers:
    - parthea
    - xylar
