travis:
  secure:
    BINSTAR_TOKEN: KOeV0Qu6JmWIdC7wJTni/v8HYaSBSMP0JDyNPdqqt6oKnbLb5dvl22ZkQY/XpvTQPnxkIEQZgrRozLQr3/cM57klbkPLhnWmHpqB8TBs5zFtkdkSs6VFBL/tKZ0OxcVThHON6pgLsqZ72Xw+UE4sLYxq3vKx5N3yzRdSlPAJa5iuhjAX+uH1HsmgjDD38z1VD8kQb3WQfU8S7OehWYz95K+szqZ2NkfiWFUjUWloHYCKRwuDPqUh74jenLezVnWOH7HUj4Ud34RqeURRut+SB9CtgsD8GWYDt8tufkDTUGY4UOWZYpbyluSq76vBHJ+LyrEQt5ZoEk51jT32UnRyuGXTPRMkaCR2AdRLzO6VNQU1VEoUcIIFfxmh8j/VfsX8BjsV8jHnouH2HIeZx7xDFzgnvus+rVJvCXhfYDCOnvHvpeJYvTLlG2pfR4FC9Ld4YaFjGX+CZLbPXodDa5qFf+yMXarv8ye48C/onYe4lEBRmZGx5C7bAtWGxiHISJ5nVVjg6Skz4KHzzfhR+3Bj9dlDIog8F00B3aEM2BwqPb04wnbTzLmsKOiCLh99jggrthKXYOebq6zgu8GAcqFAWGqbSH52NHBy4e2PVJsDz3QSs+87nk+YOYbVGSW+zkzzYDXkQgEnTuaDtEBX0M4g7usnzfSQBiN5Wkizh2qckyc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
