travis:
  secure:
    BINSTAR_TOKEN: ffJd6xV5qNJ7ucCrIZcqtPGhyCInTao9nVlNSekcG6lVMuYkGIsLZie+sDyInl+hJMUFcrGtkxq5DALPFKihkyi7h+VCg1vXExqDIjwpfFSZ4bR3/MmC35sQtvetIk1PRNdDMY8zbn6TVh6IRZOgLGqhK+5Z9koE54iFYhDCfPP8wMx5bYKKu+bArDYpKaqydtQI+3HlQd2V7FqmaYrx5IVWmRaUQ8K3JQkdQEoVPRqpyX0OnpOACiEsV302evoNryI26D7/11vtQvVdhGz2i41LDCsdaZ0jBY7l7y39gFNktyBgtt+8oCvALnmuEW/FLcCdIgvrWJay1CuHaXH1WEpL0wYMSEyuQDrYVm/1A+bDLU4kb9NFiwe2pgROVN2am0m/JBz21SxwK6LOYT2GksCxOq5Ef3boV6Vr7aXSzkVvwy5nu1wxc7Yxnkw/O7BvIqjwc5yGyNrwXlwxQD26auSIVNIQD/nJJpcII/8dsDxDDRTlat6Y47ffMEW6p+nQeBHaL/R9RQZtDaWkhBo92+k20eO7cguz43hKF3QGw94/OrGFAu4zpaQmG2PwNBopbmtuKRV3NZDg1xk4jPn6OozLFdKVgSFh/FNYkY5vkcrbXiCxaOrZYXPFgz9fpDwhrbgmPB/Pb8t088QzkOmyxFgptsMbuUDUzdEkE5OxSkU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
